name    'alkivi-samba'
version '0.1.0'
source 'https://github.com/alkivi-sas/puppet-samba'
author 'alkivi'
license 'LGPLv3'
summary 'Controls samba server'
description 'Setup samba server and handle client share'
project_page 'https://github.com/alkivi-sas/puppet-samba'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/concat', '1.0.0'
dependency 'alkivi/alkivi_base', '>0.x'
